name: Context Variables Test

# Trigger on push, pull request, and workflow_dispatch for manual runs
on:
  push:
    branches: ["*"]
  # pull_request:
  #   branches: ["main"]
  #   types: [closed]

  workflow_dispatch:

jobs:
  print-context:
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub Context Variables
        run: |
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "Github Event Action: ${{github.event.action }}"
          echo "Github Ref Name: ${{github.ref_name}}"
          echo "Github is merged? : ${{github.event.pull_request.merged}}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Job Name: ${{ github.job }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Run ID: ${{ github.run_id }}"

  print-context-on-prd:
    runs-on: ubuntu-latest
    if: ${{github.ref_name == "main"}}

    steps:
      - name: Print GitHub Context Variables
        run: |
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "Github Event Action: ${{github.event.action }}"
          echo "Github Ref Name: ${{github.ref_name}}"
          echo "Github is merged? : ${{github.event.pull_request.merged}}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Job Name: ${{ github.job }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Run ID: ${{ github.run_id }}"
