name: Add Date to GitHub Output

# Trigger on push, pull request, and workflow_dispatch for manual runs
on:
  push:
    branches: ["*"]
  # pull_request:
  #   branches: ["main"]
  #   types: [closed]
  workflow_dispatch:

jobs:
  set-date:
    runs-on: ubuntu-latest
    steps:
      # Step to set the current date as an output
      - name: Set date to output
        id: set-date
        run: |
          echo "current_date=$(date +%s)" >> $GITHUB_OUTPUT

      # Step to use the output
      - name: Print the date
        run: echo "The current date is ${{ steps.set-date.outputs.current_date }}"

